### ISSUE TITLE
Is it 100% done?

### ISSUE THREAD

**Issue by MustafaLegend1337** [Giorox/AngelionOT-Repo#304]
This project is done yet? or still 40% like the description says?

**Comment by Giorox** [comment]
@MustafaLegend1337 Project is still very far from being done, should be sitting somewhere near 50% done.

Haven't had any one working on it besides me and even so, haven't had much time to do it

**Comment by Giorox** [comment]
You and anyone else that is interested in participating are welcome to do so.

Just fork the project, look for issues to be worked in, make the edits then make a pull request and wait for analysis.
